# https://dart.dev/tools/analysis#enabling-additional-type-checks
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# https://dart.dev/tools/linter-rules
linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_redeclares
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_escaping_inner_quotes
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_print
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - directives_ordering
    - discarded_futures
    - do_not_use_environment
    - implicit_reopen
    - library_annotations
    - matching_super_parameters
    - no_self_assignments
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_single_quotes
    - prefer_void_to_null
    - public_member_api_docs
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unreachable_from_main
    - use_named_constants
    - use_raw_strings
