# https://dart.dev/tools/pub/pubspec

name: swu_data
version: 0.0.0
publish_to: none

environment: 
  sdk: ^3.3.0

dependencies:
  jsonut: ^0.2.1
  meta: ^1.12.0

dev_dependencies:
  args: ^2.4.2
  http: ^1.2.1
  lints: ^3.0.0
  path: ^1.9.0
